### ISSUE TITLE
Pagination at Plugins page shows wrong page numbers on mobile screen size

### ISSUE THREAD

**Issue by Lubje** [filamentphp/filamentphp.com#122]
When going through the pages with plugins (https://filamentphp.com/plugins), with the filters as shown in the screenshot below, the pagination shows wrong page numbers when you go from page 2 (second last) to page 3 (last).

I've checked it with the following browsers:

On mobile Android phone:
- Brave version 1.56.20, Chromium 15.0.5790.171
- Chrome version 115.0.5790.166

Desktop (only happens on the smaller breakpoints):
- Chrome version 115.0.5790.170 (Official Build) (x86_64)
- Brave version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (x86_64)

![filamentphp com plugins pagination bug](https://github.com/filamentphp/filamentphp.com/assets/3015427/92873673-c768-4b6a-a69c-53848ae776bf)

**Comment by HassanZahirnia** [comment]
Should be fixed. Can you check again @Lubje ?

**Comment by Lubje** [comment]
Check check double check!

**Comment by HassanZahirnia** [comment]
Great! 😊 Thanks for reporting this issue!

**Comment by Lubje** [comment]
Anytime!
Thank you guys for FilamentPHP, it looks like the solution I needed for all my half completed side projects :)
Excited to use it next week, for the very first time.
