### ISSUE TITLE
can we have first-party plugins in side bar

### ISSUE THREAD

**Issue by ariaieboy** [filamentphp/filamentphp.com#15]
I have a suggestion about the document page. it's good to have first-party plugins in the sidebar under the products documentation link. 

we have them listed on main github repo readme but have it in documentation site gonna help alot

**Comment by danharrin** [comment]
Originally we did this, but it made the sidebar too crowded. Now, the links to first party plugin docs can be found in our Plugins section, the same as all other plugins.

https://filamentphp.com/plugins/spatie-media-library
