### ISSUE TITLE
Installing locally without `spatie/laravel-comments`?

### ISSUE THREAD

**Issue by adevade** [filamentphp/filamentphp.com#20]
I'm trying to install your website on my local machine, to submit some pull requests.
But I don't have a licence for Spaties Laravel Comments package.

When Composer is installing, I get the following prompt and it just hangs there:
```
- Downloading spatie/laravel-comments (1.1.3)
- Downloading spatie/laravel-comments-livewire (1.2.5)
Authentication required (satis.spatie.be)
Username:
Password:
```

How can I install this repo locally?

**Comment by danharrin** [comment]
Unfortunately you would need a license, sorry
