### ISSUE TITLE
Duplicate column `author_name` in database migrations

### ISSUE THREAD

**Issue by adevade** [filamentphp/filamentphp.com#21]
When installing and running migrations for this site, I got the following error: `SQLSTATE[HY000]: General error: 1 duplicate column name: author_name (SQL: alter table "plugins" add column "author_name" varchar)`

On the [original Links migration](https://github.com/filamentphp/filamentphp.com/blob/8a694fe5aa4c7f02f2d0b97bb076c5483a604497/database/migrations/2021_12_16_233557_create_links_table.php#L18-L19), `author_name` is not added.
But on the [original plugins migration](https://github.com/filamentphp/filamentphp.com/blob/8a694fe5aa4c7f02f2d0b97bb076c5483a604497/database/migrations/2021_12_16_233557_create_plugins_table.php#L18-L20), it is:

It is then [added again to the Plugins table](https://github.com/filamentphp/filamentphp.com/blob/8a694fe5aa4c7f02f2d0b97bb076c5483a604497/database/migrations/2022_03_30_152650_add_author_name_column_to_links_and_plugins_tables.php#L21) in a later migration, causing the error.

**Comment by zepfietje** [comment]
Thanks for reporting, fixed it!

**Comment by danharrin** [comment]
@zepfietje this has broken deployments on the website

**Comment by danharrin** [comment]
![image](https://user-images.githubusercontent.com/41773797/193414678-c46cb3f9-f8c4-45ea-9fc1-51db38bdf8fc.png)

**Comment by zepfietje** [comment]
Oh might that be due to the renaming of the migration file?

**Comment by zepfietje** [comment]
@danharrin, deployments should be fine now: https://github.com/filamentphp/filamentphp.com/pull/24.
