### ISSUE TITLE
Images Not Displaying

### ISSUE THREAD

**Issue by Adams-Ijachi** [filamentphp/filamentphp.com#226]
Hello guys great job, it seems the images in the websites aren't loaded even on the readme
I am new to open source and would love to help out with this if you could let me know how to help
thanks and great job (new filament user)

**Comment by HassanZahirnia** [comment]
Hey, welcome to Filament! 😊

Can you please provide more information on which "images" are not loading? Page link and a screenshot would help.
And also what do you mean by "readme"?
