### ISSUE TITLE
version in title tag

### ISSUE THREAD

**Issue by QuantBits** [filamentphp/filamentphp.com#303]
Would be nice to have the Filament version in the title of the docs. First link is to 2.x docs and last is to 3.x, but there's no way to tell without hovering/clicking

<img width="648" alt="Screenshot 2024-01-06 at 21 41 52" src="https://github.com/filamentphp/filamentphp.com/assets/784092/a6e1661b-36a0-4739-995e-8e6c9308d857">

**Comment by danharrin** [comment]
Google search result titles do not correlate to the actual `<title>`. Stupid, I know. But they get optimised before they are shown to the user, to give them a better overview of what the difference in results is.

**Comment by QuantBits** [comment]
Sorry for opening this again @danharrin but this was a change done in the Laravel docs recently, and it seems to have helped. While not every result will use the <title> but a custom one, it at least helps a tiny bit. I'll attach two screenshots, one from the thread here: https://github.com/laravel/laravel.com/pull/300 and one from how the results look now.

<img width="640" alt="Screenshot 2024-01-07 at 21 01 47" src="https://github.com/filamentphp/filamentphp.com/assets/784092/6b225d66-3c9f-4cfe-8b35-a37e2c751bbc">
![258459896-5225f12e-22d2-49ec-afb0-5409ae6ed40a (1)](https://github.com/filamentphp/filamentphp.com/assets/784092/d13b2e8f-3a0d-4763-9ecd-192b33986659)

Just wanted to add what was done there :)

**Comment by danharrin** [comment]
You can make a PR if you wish, not sure of the work involved
