### ISSUE TITLE
Applying filters does not reset page number

### ISSUE THREAD

**Issue by Fludem** [filamentphp/filamentphp.com#307]
Applying filters should reset the page back to page 1.

Take this example:

No filters are applied and there are 10 pages of plugins.
User goes to page 5 then clicks Developer tools.

The users screen says no plugins found and it isn't clear on screen that they just need to go back to page one.

**Comment by HassanZahirnia** [comment]
Thanks for reporting this issue. 🙏 I've fixed the problem. ✅
