### ISSUE TITLE
Call to undefined method App\Models\Plugin::factory()

### ISSUE THREAD

**Issue by abdelhamiderrahmouni** [filamentphp/filamentphp.com#373]
![Screenshot 2024-03-26 102049](https://github.com/filamentphp/filamentphp.com/assets/26693672/f09144af-6e92-4dcc-82ce-309cc9fb9bd1)

I have got this error during the seeding of the database on a fresh install of this repository

**Comment by HassanZahirnia** [comment]
Hi there,

This repo is specifically engineered for the filamentphp.com website. The database containing the website's content is already included in the repo, so there's no need to perform any seeding operations.
