### ISSUE TITLE
Syntax highlighting not showing on Action -> Modals

### ISSUE THREAD

**Issue by izzudin96** [filamentphp/filamentphp.com#443]
Syntax highlighting not showing on this page.

https://filamentphp.com/docs/3.x/actions/modals 

![image](https://github.com/filamentphp/filamentphp.com/assets/34004451/4fd45651-47dd-43af-ae6b-4acce4ad3ff8)

**Comment by HassanZahirnia** [comment]
Hi there, thanks for reporting this issue, I've rebuilt the docs and it should be fixed now! 😊👍
