### ISSUE TITLE
Broken HTML in "Grouping Rows" screenshot

### ISSUE THREAD

**Issue by ConnorHowell** [filamentphp/filamentphp.com#51]
On https://beta.filamentphp.com/docs/3.x/tables/grouping there's broken HTML in all the screenshots. Not sure if this is also an issue with the table builder itself or how the docs are built?
![image](https://github.com/filamentphp/filamentphp.com/assets/4037845/adb25b4b-e535-4cb9-91ca-5f173ea901dc)

**Comment by zepfietje** [comment]
Thanks for reporting.
We're aware of this issue (caused by a Livewire bug).
