### ISSUE TITLE
[ Suggestion ] A special area on site for projects that made with filament.

### ISSUE THREAD

**Issue by ibrahimBougaoua** [filamentphp/filamentphp.com#547]
**Hi,
It is nice to add a special area at site for projects that are made with filament,
I think this is the best way to show the power of filament and what we can do with it.**

**Comment by HassanZahirnia** [comment]
Thanks for submitting your idea Ibrahim. 🙏😊 Next time please use the Discord chat to discuss any ideas instead of using the Issue section of this repo.

**Comment by ibrahimBougaoua** [comment]
> Thanks for submitting your idea Ibrahim. 🙏😊 Next time please use the Discord chat to discuss any ideas instead of using the Issue section of this repo.

**Okay Thanks.**
