### ISSUE TITLE
Wrong logo fill

### ISSUE THREAD

**Issue by zepfietje** [filamentphp/filamentphp.com#566]
@danharrin, this new logo doesn’t have the same monochrome color as the others. The black fill should probably be removed or changed to current color.

https://github.com/filamentphp/filamentphp.com/blob/87a78c35476fa636e8a6c50a556fd9ea9332f043/resources/views/components/sponsors/larafast.blade.php#L18

**Comment by danharrin** [comment]
Ah, I didn't even notice
