### ISSUE TITLE
Missing result in search

### ISSUE THREAD

**Issue by scarpeneintesys** [filamentphp/filamentphp.com#574]
When i try to search for "make:filament-resource" the only result shown is:
![image](https://github.com/user-attachments/assets/529dc3b9-82fe-4141-995f-e11c7d0bf5d4)
that point to https://filamentphp.com/docs/3.x/panels/clusters#code-structure-recommendations-for-panels-using-clusters
I think there is some results missing because there are for example results here.
https://filamentphp.com/docs/3.x/panels/getting-started that explain the command.

**Comment by danharrin** [comment]
Algolia indexes the docs, not the Filament team manually, so I'm going to close this as there's not much we can do.
