### ISSUE TITLE
Tricks link is not working 

### ISSUE THREAD

**Issue by faizananwerali** [filamentphp/filamentphp.com#71]
[https://filamentphp.com/tricks/turbolinks-admin](https://filamentphp.com/tricks/turbolinks-admin) 

This link is from version 2. Which is now inaccessible. How do I access it? Specifically v2 panel.

All tricks link are down. I don't want migrate my app to version 3 yet. Anyhow can I access v2 tricks links.

**Comment by HassanZahirnia** [comment]
Hey! The old content from the v2 website is now accessible via https://v2.filamentphp.com

Also if you re-try the link you provided you'll notice it will work this time.

In the new website we switched to static site for managing content, so if you want to submit a trick or an article, the instructions are in the repo's README: https://github.com/filamentphp/filamentphp.com#submitting-an-article-to-the-community-section

**Comment by danharrin** [comment]
Redirects are in place now for old content
