### ISSUE TITLE
Add Query string support

### ISSUE THREAD

**Issue by archilex** [filamentphp/filamentphp.com#73]
It'd be great if filtering by search, version, free/paid, categories, etc. could set query string parameters so it'd be easy to reload the page and keep your place.

**Comment by HassanZahirnia** [comment]
Hey! Thanks for sharing your ideas.😊  This has already been on my TODO list for a while now. I'll let you know when I implement it.

**Comment by HassanZahirnia** [comment]
@archilex I've added history and URL parameters for the Plugins and Community pages. 👍

(Although it has not been implemented for selecting categories yet because of some technical difficulties)
