### ISSUE TITLE
Dark mode doesn't work.

### ISSUE THREAD

**Issue by ibrahimBougaoua** [filamentphp/filamentphp.com#74]
Hi,
Dark mode doesn't work.
When i clicked in button,the dark mode doesn't change.

https://filamentphp.com/plugins

**_Thanks, a lot for new features._**

**Comment by danharrin** [comment]
The button doesnt trigger dark mode. It filters plugins to only show those with dark mode support

**Comment by ibrahimBougaoua** [comment]
Ah,Okey.
Thanks.
