### ISSUE TITLE
What happened to Tricks?

### ISSUE THREAD

**Issue by joligoms** [filamentphp/filamentphp.com#81]
It seems like tricks have moved to community along with other articles. But apart from that, why are there so few trick articles now? It was good stuff, hahaha. The filter for versions 1, 2 and 3 are not working either. Is the website update still in progress?

**Comment by joligoms** [comment]
Oh, alright. I see the old version is still on: https://v2.filamentphp.com/tricks

**Comment by HassanZahirnia** [comment]
Hey! The old content from the v2 website is now accessible via https://v2.filamentphp.com

And yes the website update is still in progress as the creators are slowly migrating their plugins and content to the new format.

**Comment by danharrin** [comment]
The tricks are now part of the "Community" section, as a category

**Comment by joligoms** [comment]
Thank you very much for your help. The website is even better now.
